CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# For split: central (left) fetches and proxies right half battery too
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y                                                                                                  
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# ZMK Studio: live remap keys without reflashing (newer ZMK feature)
# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=y

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n # Prevents Windows from dropping BLE connection when it re-subscribes to GATT notifications